### ISSUE TITLE
Update migration about parser rules

### ISSUE THREAD

**Issue by elisherer** [webpack/changelog-v5#19]
Needs to add to the deprecation and migration docs that `requireEnsure: false` is no longer accepted.

webpack.config.js
```
    rules: [
      { parser: { requireEnsure: false } },
```
yields the error:
```
ValidationError: Invalid parser object. Json Modules Plugin has been initialized using a parser object that does not match the API schema.
 - parser has an unknown property 'requireEnsure'. These properties are valid:
   object { parse? }
```

**Comment by jamesgeorge007** [comment]
This config applies to all modules types. JS and e. g. JSON modules types. `parser.requireEnsure` is only valid for JS modules, while JSON module do not accept this option. They probably have to add a test: `/\.[cm]?js$/` to make it only apply to JS module types.

**Comment by dasler-fw** [comment]
> This config applies to all modules types. JS and e. g. JSON modules types. `parser.requireEnsure` is only valid for JS modules, while JSON module do not accept this option. They probably have to add a test: `/\.[cm]?js$/` to make it only apply to JS module types.

Could you please explain in more details?
